DROP TABLE IF EXISTS Rooms;

CREATE TABLE IF NOT EXISTS Rooms (
  RoomId TEXT PRIMARY KEY,
  RoomCreated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  RoomUpdated DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TRIGGER IF NOT EXISTS Rooms_updated
AFTER UPDATE ON Rooms
BEGIN
  UPDATE Rooms
  SET RoomUpdated = CURRENT_TIMESTAMP
  WHERE RoomId = NEW.RoomId;
END;